# Generated by Django 3.2.7 on 2023-11-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('content', models.TextField(default='空空如也', verbose_name='文章内容')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
