# Generated by Django 3.2.7 on 2023-11-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(default='python', max_length=128, verbose_name='文章标签'),
        ),
    ]
