# Generated by Django 3.2.7 on 2023-11-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='update_at',
        ),
    ]
